apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: proxy
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: secret_username
        valueFrom:
            secretKeyRef:
              name: dbcred
              key: username
      - name: secret_password
        valueFrom:
            secretKeyRef:
              name: dbcred
              key: password      
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: foo
      secret:
          secretName: dbcred
      
