apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    server: proxy
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

      
