apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    layer: cache
spec:
  containers:
  - name: redis
    image: kubernetes/redis:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master
      name: config
    env:
      - name: env1
        valueFrom:
          configMapKeyRef:
            name: env-config
            key: key1
  volumes:
    - name: config
      configMap:
          name: redis-config
          items:
            - key: configmap/redis-config # path in host
              path: redis.conf # path in container
